### ISSUE TITLE
Error installing with Carthage

### ISSUE THREAD

**Issue by p-z-l** [NSHipster/SwiftSyntaxHighlighter#2]
I tried install SwiftSyntaxHighlighter by Carthage.
Here's my Cartfile:
`github "NSHipster/SwiftSyntaxHighlighter" ~> 0.0.1`

Then I run `Carthage update` and get this error(every times):

![carthage-error](https://user-images.githubusercontent.com/43706386/59970879-79f7c680-95a3-11e9-96c1-d4155a7344db.png)

```
$ carthage update
*** Fetching SwiftSyntaxHighlighter
*** Checking out SwiftSyntaxHighlighter at "0.0.2"
*** xcodebuild output can be found in /var/folders/jf/kqw7xjn51m1b2jfg6956k3t00000gr/T/carthage-xcodebuild.hxbd2e.log
*** Skipped building SwiftSyntaxHighlighter due to the error:
Dependency "SwiftSyntaxHighlighter" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/NSHipster/SwiftSyntaxHighlighter/issues/new
```

**Comment by mattt** [comment]
Installation with Carthage isn't supported. Please use Swift Package Manager instead.
